### PR TITLE
Add organizers

### PR DESCRIPTION
**Pull request by chrisdickinson**
screen shot 2014-06-12 at 6 37 17 pm
screen shot 2014-06-12 at 6 37 32 pm

### CODE REVIEW

**Comment by hackygolucky** [comment]
Ah, hold up on merge please. I need to confirm a detail with @crabasa :100: :koala: :partly_sunny: :sunglasses:

**Comment by nvcexploder** [comment]
Could mine be any more ridiculous?

**Comment by hackygolucky** [comment]
Hah! nope @nvcexploder 

@chrisdickinson a few minor tweaks as requested by Carter and I.
Carter should be the last in the list. I should be first. I need the title Curator somewhere in there, so if need be just take it on the beginning of the copy.

via Carter:
"You can just refer to me as the "founder" and my role is that of a mentor and CPA." 

Pleeeeease :)

**Comment by hackygolucky** [comment]
:+1: :+1: :+1: :+1:

**Pull request merged**
