### PR TITLE
Call for Makers announcement

### PR DESCRIPTION
**Pull request by hackygolucky**
Announcing the Call for Makers to submit projects and implement awesomeness for the JS Art Interactive Exhibit over the course of CascadiaJS 2014.

Please look especially for typos, ambiguity, or oversights that should be added in. Explicit is good!

cc @chrisdickinson @nvcexploder @phated @ThisIsJohnBrown @benpurdy

Note: I didn't make it a separate repo for discoverability's sake. Past precedent set submissions of this nature in this repo.

### CODE REVIEW

**Comment by randallagordon** [comment]
I'm gonna need a web socket. Maybe two.

**Comment by hackygolucky** [comment]
hah oh gah!

**Comment by hackygolucky** [comment]
Also we should probably have a picture of fun stuff at the top, for reasons.

**Comment by nvcexploder** [comment]
:+1: I think this looks great @hackygolucky!

**Pull request merged**
